# Generated by Django 4.0.4 on 2022-04-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tether_balance', models.FloatField(default=0)),
                ('bitcoin_balance', models.FloatField(default=0)),
            ],
        ),
    ]
