# Generated by Django 4.0.4 on 2022-04-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_asset', models.CharField(max_length=20)),
                ('sell_asset', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MarketTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('buy_asset', models.CharField(max_length=20)),
                ('sell_asset', models.CharField(max_length=20)),
                ('in_price', models.FloatField()),
                ('close_date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LimitTransaction',
            fields=[
                ('markettransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.markettransaction')),
                ('in_price', models.FloatField()),
            ],
            bases=('transactions.markettransaction',),
        ),
        migrations.CreateModel(
            name='LimitTransactionHistory',
            fields=[
                ('markettransactionhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.markettransactionhistory')),
                ('in_triggered', models.BooleanField(default=False)),
            ],
            bases=('transactions.markettransactionhistory',),
        ),
        migrations.CreateModel(
            name='SignalTransaction',
            fields=[
                ('markettransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.markettransaction')),
                ('in_price', models.FloatField()),
                ('target_price', models.FloatField()),
                ('stop_loss', models.FloatField()),
            ],
            bases=('transactions.markettransaction',),
        ),
        migrations.CreateModel(
            name='SignalTransactionHistory',
            fields=[
                ('markettransactionhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.markettransactionhistory')),
                ('target_price', models.FloatField()),
                ('stop_loss_price', models.FloatField()),
                ('in_triggered', models.BooleanField(default=False)),
                ('target_triggered', models.BooleanField(default=False)),
                ('sl_triggered', models.BooleanField(default=False)),
            ],
            bases=('transactions.markettransactionhistory',),
        ),
    ]
