# Generated by Django 4.0.4 on 2022-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markettransaction',
            name='amount_to_sell',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
